### ISSUE TITLE
“Unknown error” when I try to browse media

### ISSUE THREAD

**Issue by ralphrtm** [koying/jellyfin_ha#31]
Home Assistant version:  container core-2022.6.7
Jellyfin Server: container  10.8.0
Jellyfin-HA: addon 1.1.1
Kodi: Matrix 19.4

Hello! I can’t browse my file from home assistant in order to play media to my kodi players. Whenever I try to do it, it prompt “Unknown errror” 

![Screenshot 2022-06-25 at 02 01 01](https://user-images.githubusercontent.com/37366255/175749829-ec84ec85-9739-4d25-87d3-b8de8746b5fd.png)

I tried to reinstall the addon, even on a fresh install of home assistant. I also tried the 1.0.8 version of jellyfin-ha as a similar issue has been already mentioned. Still nothing…

But, if I delete my manual playlist in jellyfin I can browse media again

Here the logs from Home assistant:

2022-06-25 02:13:31 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [2717597736] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 161, in websocket_browse_media
    media = await async_browse_media(hass, msg.get("media_content_id", ""))
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 112, in async_browse_media
    item = await _get_media_item(hass, media_content_id, None).async_browse()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 86, in async_browse
    return await self.async_media_source().async_browse_media(self)
  File "/config/custom_components/jellyfin/media_source.py", line 128, in async_browse_media
    return await async_library_items(self.jelly_cm, media_content_type, media_content_id, canPlayList=False)
  File "/config/custom_components/jellyfin/media_source.py", line 289, in async_library_items
    identifier=f'{Type2Mediatype(item["Type"])}{IDENTIFIER_SPLIT}{item["Id"]}',
  File "/config/custom_components/jellyfin/media_source.py", line 157, in Type2Mediatype
    return switcher[type]
KeyError: 'ManualPlaylistsFolder'

Thanks

**Comment by manuel-rw** [comment]
I'm having the same issue with the version from HACS. Why hasn't there been a release for this?

**Comment by GetLifty** [comment]
This error still seems to occur. It sometimes goes away but then comes back later.

**Comment by alanmilinovic** [comment]
I can confirm that it is still there. I guess as this project is no longer maintained it will never be fixed.

**Comment by manuel-rw** [comment]
I think this actually has been fixed, but the update hasn't beel rolled out to HACS?
https://github.com/koying/jellyfin_ha/compare/v1.1.1...main

Has anyone tried running this from source? Perhaps this is possible with HA

**Comment by alanmilinovic** [comment]
> I think this actually has been fixed, but the update hasn't beel rolled out to HACS? [v1.1.1...main](https://github.com/koying/jellyfin_ha/compare/v1.1.1...main)
> 
> Has anyone tried running this from source? Perhaps this is possible with HA

Yes, that is the fix that is solving the issue partially. The problem is, error is still there, from time to time. I just navigate one folder back and then error is gone.

**Comment by manuel-rw** [comment]
Judging from the commit message, this plugin might not be able to handle unknown types or items in your library?
That would also explain why the author here didn't accommodate for all types, if they don't use it themselves, hence throwing the this error

**Comment by manuel-rw** [comment]
Is there an active fork? I haven't checked yet

**Comment by alanmilinovic** [comment]
> Is there an active fork? I haven't checked yet

https://github.com/Cyr-ius/jellyfin_ha

**Comment by Stooovie** [comment]
Unfixed as of September 2023.
